apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-inference-svc
spec:
  type: NodePort
  selector:
    app: cats-dogs-inference
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080
