apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-api
  labels:
    app: cats-dogs
    component: api
spec:
  type: NodePort
  selector:
    app: cats-dogs
    component: api
  ports:
  - name: http
    port: 8000
    targetPort: http
    nodePort: 30080

---
apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-ui
  labels:
    app: cats-dogs
    component: ui
spec:
  type: NodePort
  selector:
    app: cats-dogs
    component: ui
  ports:
  - name: http
    port: 7860
    targetPort: http
    nodePort: 30081

---
apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-prometheus
  labels:
    app: cats-dogs
    component: prometheus
spec:
  type: NodePort
  selector:
    app: cats-dogs
    component: prometheus
  ports:
  - name: http
    port: 9090
    targetPort: http
    nodePort: 30090

---
apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-grafana
  labels:
    app: cats-dogs
    component: grafana
spec:
  type: NodePort
  selector:
    app: cats-dogs
    component: grafana
  ports:
  - name: http
    port: 3000
    targetPort: http
    nodePort: 30300
