apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-inference-svc
spec:
  type: NodePort
  selector:
    app: cats-dogs-inference
  ports:
    - name: api
      port: 8000
      targetPort: 8000
      nodePort: 30080

    - name: ui
      port: 7860
      targetPort: 7860
      nodePort: 30081
